import libs = pcg-cpp%lib{pcg-cpp}

for test_cpp : src/cxx{* -pcg-test -pcg-test-no-advance}
{
    test_name = $name($test_cpp)
    ./ : exe{$test_name} : $test_cpp $libs
    if($test_name != "check-pcg64_unique")
    {
        exe{$test_name} : testscript
    }
}